apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-azurefile-csi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: deployment-azuredisk
    spec:
      containers:
      - name: nginx-azurefile
        image: nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name: volume
            mountPath: "/mnt/azurefiledynamiccsi"
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: dynamic-azurefilecsi-pvc