apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-azurefilecsi-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi